openapi: 3.1.0
info:
  title: poster-api
  description: API for managing posters.
  version: 1.0.0

servers:
  - url: https://api.posters.com/v1
    description: Production server

paths:
  /posters:
    get:
      summary: List all posters
      description: Returns a list of all posters.
      responses:
        '200':
          description: A list of posters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Poster'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Add a new poster
      description: Adds a new poster to the list.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Poster'
      responses:
        '201':
          description: Poster created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poster'
        '400':
          description: Invalid request data
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /posters/{id}:
    get:
      summary: Find a poster by ID
      description: Returns a single poster identified by its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The unique ID of the poster.
          schema:
            type: integer
      responses:
        '200':
          description: Poster details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poster'
        '404':
          description: Poster not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a poster
      description: Updates the information of an existing poster.
      parameters:
        - name: id
          in: path
          required: true
          description: The unique ID of the poster to update.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Poster'
      responses:
        '200':
          description: Poster updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poster'
        '404':
          description: Poster not found
        '400':
          description: Invalid request data
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a poster
      description: Deletes a specific poster from the list.
      parameters:
        - name: id
          in: path
          required: true
          description: The unique ID of the poster to delete.
          schema:
            type: integer
      responses:
        '204':
          description: Poster deleted successfully (No content)
        '404':
          description: Poster not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Poster:
      type: object
      required:
        - imageUrl
      properties:
        id:
          type: integer
          description: Unique identifier for the poster.
          readOnly: true
        imageUrl:
          type: string
          description: The URL of the poster image.
          examples:
            - "https://images.posters.com/posters/poster1.jpg"
        title:
          type: string
          description: The title or description of the poster.
          examples:
            - "Poster"
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
